packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  electron-winstaller: false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@merittdev/avion@0.2.0'
  - electron@42.5.1
